
\section{Analysis of Health Construct Interviews}

\subsection{Methodology}

Eight interviews were conducted in a semi-strctured format. The participants in the interviews included 3 alternative/complementary therapists, 2 GP's and 3 ordinary people with experience of healthcare, both western and complementary.

The questions which were asked were as follows:
\begin{enumerate}
\item What does the term health mean to you? 
\item Have you had any health problems in the past that you would like to discuss?
\item How do you believe that health can be promoted and sustained?
\item What kinds of treatments do you feel are effective? 
\item How are they effective?
\item What has been your experience with the official medical sector?
\item What has been your experience with the complementary medicine sector?
\item When you are sick, what types of help or treatment do you find most useful?
\item What do you think are the major causes of sickness (for you or others)?
\item What people or qualities do you associate with health?
\end{enumerate}


The Interviews were conducted between October 2009 and January 2010. 

\subsection{Analysis}

The interviews were first coded using an inductive coding procedure. In this, the codes were developed from the interview transcripts themselves, allowing the participants to define the nature of the analysis (in some sense). Following completion of the interviews and first coding, the interviews were then recoded using the entire database of codes which had been developed throughout the analysis procedure.
During this phase redundant codes were also removed. Following the coding procedure, codes weree combined into thematic units where appropriate. For example, the many codes relating to health were combined into an overall health code.

This analysis will look at the material collected and analysed in the following ways:

\begin{enumerate}
\item Analysis on the level of the group – GP's, ordinary people, and alternative therapists. All of these participants seemed to have different perspectives on the matters concerned, and this section will highlight the commonalities and differences between them
\item  Analysis of coding structures, across groups
\item Analysis of themes across the entire sample 
\end{enumerate}

\subsection{Overall theme}

In these interviews, a number of important themes emerged from the data. These are noted here and further developed throughout the test. These major themes were as follows:
\begin{enumerate}
\item Health – internal or externally determined. This theme seemed to stratify respondents into groups. Some respondents (alternative therapists mostly) seemed to look at the determinants of health as being mostly cognitive and emotional, while others (GP's mostly) seemed to look at more external determinants of health, such as pathogens and social status. The ordinary people interviewed in this research project tended to incorporate elements from both of these perspectives.
\item Doctors as prescribers, alternative therapists as facilitators – the alternative therapists tend to talk about facilitating people towards health, while the doctors tend to talk about curing people. 
\item Energy versus biology – doctors tend to talk about biology, alternative therapists tend to talk about energy. 

\end{enumerate}



\subsection{Group Analysis}

\subsubsection{Alternative/Complementary Practitioners}

\paragraph{Participant Information}

Three participants were interviewed as part of this group. One was a shaitsu and Reiki practitioner, one was a spiritual healer and the third was an acupuncturist. They were all recruited from the Cork area following email contact through an alternative therapy website. 

\subsection{Major Themes}
\begin{enumerate}
\item Health is caused by internal rather than external factors
\item Energy model of health – reference to vital forces, meridians and s on
\item They tend to talk about being facilitators rather than healers. They put more of the responsibility on the patient (self-healing model)
\end{enumerate}

\subsection{Coding Analysis and Examples}




\subsection{Health as balance}

Again, this code occurred quite frequently, but only in the transcripts of the alternative therapists. Some examples and discussions follow below. 

``So these are the processes in the mind, so again, health in respect to that, to emotions, mental energy very much keeping on a balanced level – Alternative Therapist 3''

We see here that the participants believes balance to be key to all health, on an emotional, physical and mental level. We can also note the focus on energy, which will be examined further below. We can also see here a focus on processes, that these elements are constrantly moving, which is borne out in the quote below. 

``The same thing with the emotions, keeping them moving, keeping them flowing, ammmm – Alternative Therapist 3''
Again, we can see the focus on movement, that emotional expressions should be facilitated, and we can imply conversely that stagnation of emotions is unhealthy. This is interesting in that there is much psychological evidence that suggests that secrets and unexpressed emotions can link into physical health problems. 

``P:Same thing, the imbalance-
I:mmmm
P:Of emotions, imbalance of mental thinking imbalance of sleep not sleep to much sleep ahhh and then what you're putting into the body obviously, and also what you're putting into the body if you're sitting in front of a computer for too long, if you're sitting in front of a TV too long, you're putting too much electromagnetic energy on the mobile phone for too long so generally, ammm so you've cardio-vascular health we need balance there-- Alternative Therapist 3''

We can see from the above quote that while health is conceived of as balance, sickness is thought to result from either too much or too little of a particular substance or process. We can note the focus on both mental and physical imbalance here, this linking of levels of existence is a theme that pervades the entire transcripts, and  will be examined in detail later. 

\subsection{Energy Model of Health}

Another code which occurs throughout the transcripts of the alternative therapists is this notion of \textit{elan vital}, or life force. This is one of those ideas with a strong resonance thoughout human history, as multiple cultures appear to have developed in independently. We'll look at this in more detail using excerpts from the transcripts below. 
``how do I think they work? Well....from doing different treatments....like shiatsu, so which works on the energetic plane – Alternative Therapist 1''

We note here, that when the respondent was asked how some of the treatments used by him worked, he focuses immediately on shiatsu (a form of Japanese massage) which is the treatment he uses most often in his professional practice. We can also see that he constructs this treatment as operating on an energetic plane, which presumably means that it effects the person on another level from the physical. This theme continues throughout the transcripts of the alternative therapists, and appears to be the explanatory model utilised by the majority of them. 

``you actually work energy channels that ammm...remind....the person to put energy in certain places. Yeah, like I would press certain acupuncture points, work certain energy channels...- Alternative Therapist 1''

As we can see from this excerpt, the practitioner seems to link this energy body to the physical body, such that changes in physical pressure on certain points, suggesting that these two parts of a person are interlinked and occupy the same space. 

``it is too easy to say mind body soul but roughly its pretty much that, physical energy, taking the energy from your food and translating that into nutrition into energy and accommodating that and then expelling energy and expelling waste products efficiently that's the physical side of things energy then – Alternative Therapist 3''

However, in this excerpt we have a very different interpretation of energy from this respondent. The energy she describes links up exactly with what we would consider energy to be (the breakdown of food into sugars), so this definition appears to differ quite substantially from the one given by Alternative Therapist 1 above, which suggests some conceptual confusion. Further excerpts will probably make this clear, however. 

``There's emmm very common ahhh which my professor used to say – if ahhh if you want to do exams, if you're studying, eat well. He says the spleen produces your blood your red blood cells – Alternative Therapist 3''

This extract is interesting, in that the energy model is extended here to apply to mental efforts also. We can also see the linkages between physical and mental health here. Again, we see examples of organs in the body being associated with particular states and traits of the mind. 

`` In france they use digestifs, and apertifs, and thats that's the same thing, you know the same as preparing the energetics to assimilate....transform and bring forth the energy from that food very very carefully, and if you do that, then you're going to have Chi and if you've Chi the the character for Chi in Chinese medicine, or sorry in Chinese language ammm the I'll draw for you is is similar to that and basically what it symbolising is a fire, a pot with rice in the pot and steam rising from it so the pot is sitting over the fire cooking the soup – Alternative Therapist 3''

Again here we see the linkage of physical nutrition and energy. This respondent links the physical act of eating to the life force describes as Chi, suggesting that this Chi terminology may be a descriptor for the sugars and other prodcuts needed to keep humans alive. Again, we see the notion that food also gives us this energy, which is seperate from the physical value of food, and that this is the energy which can impact our health and the lack of which causes us to become sick. 



``So again, when you say how do I think it works thats how I think it works as well manipulating energy
I:mmmm
P: ammm, the energy has to be there first day or first place, so someone is very depleted then often I have to make sure I that we get them to a place where they can that I can manipulate energy because if it's not there, I'm only going to deplete them much more – Alternative Therapist No 3''

Here we see a construction of this energy, or Chi in that it can become depleted, and that the task of the therapist is to increase this energy in order to allow their methods to work on the patient. 

``am manipulating pockets of either static or depleted for replete excessively replete some energy in the body and ahhh....
I: that effects change?
P: Yeah, exactly, yeah, yeah. So thats I suppose my limited way of understanding it and the rest then is down to patient cooperation, really, go and do your rest, we've told you enough here – Alternative Therapist 3''

In this excerpt we can see that the problem is constructed as one of imbalance, either there is too much energy, or too little and that the role of the therapist is to balance these energy pockets across the person to ensure that health returns. 



\subsection{Emotional Health}

This code was predominantly used by the alternative therapists, but also appeared a number of times in one of the GP transcripts. We'll look at and discuss some of the examples from the alternative therapists section below. 

``P: Ammm...so....a non-stressful lifestyle you know? And a ...fun, laughter, that you do things that you like to do. - Alternative Therapist 1''

``o its more preventative, in its focus more and its all about balance being in
P: that's all the physical side
I: oh?
P: and then I try to definitely you know, meditate, 
I: mmmm, mmmm
P: and ehhhh, focus on my emotions and my thoughts – Alternative Therapist 1''

We can see from these quotes that for many of the alternative therapists, emotional well being is an important factor in their construction of health. They tend to construct health as being situated in a context whereby emotional well being is extremely important and that it forms an integral part of health. This links in with the research suggesting that optimism is associated with health, something which will be discussed later and which appears to be a construction made by almost all of the participants in this study. 

``P: Most causes are the emotional-
I:mmmm, mmmm-
P:and so the body is really reacting and that
I:mmmm, mmmm
P: So thats – thats why we say mind and body, you know that kind of a balance – Alternative Therapist 2''

For this respondent, the emotions are the primary driver of sickness or health. She seems to construct health as being something primarily determined by one's emotional outlook, rather than resulting from pathogens or the environment. Its interesting that this is exact opposite opinion offered by the GP's who were included in this study. 

``emotional energy has to be very well balanced we have to breathe our emotions, we cannot suppress them am they have to (pause) be (pause) tuned in and out of the body very carefully. - Alternative Therapist 3''

As we can see here, the construction of the importance of emotions runs throughout all of the transcripts of the alternative therapists. This respondent links the emotional expression with the breathing, that they have to be taken in and let out very regularly. He seems to construct them as something which can have great physical impact, and should be treated with respect.


``ahhh it it if used in itself it may not answer the whole problem because people come not only with a condition, they come with with a condition attached to their own bodies its got feelings, its got thoughts preconceptions, its got worries, etcetera- - Doctor 2''

Although this section is dealing with the transcripts of the alternative therapists, this quote is included here to gain a different perspective on emotional health. We can see from this quote that this respondent possesses a radically different construction of emotions and their relationship to health. For him, the body is the primary part, and he constructs this using depersonalising language (it) the body is the important part, but it has all of these messy emotions and thoughts attached to it which complicate matters. The contrasting quotes here nicely illustrate the differences in construction between the alternative therapists and the general practitioners. 


\subsection{Personal Effort}

Again, this code appeared mostly in the transcripts of the alternative therapists, although it also appeared in the transcripts of one of the doctors. 

``reflex points, If a person is not willing to work on themselves and to get better, you can do whatever you want, and they- Alternative Therapist 1''

``I: so it requires their willingness to take part in the procedure aswell - Alternative Therapist 1''

These quotes serve to illustrate a point made again and again by the alternative therapists and to a lesser extent by doctors. That point is that people are ultimately responsible for their own health, regardless of what help they get from a healthcare professional. 

``Yeah, but again it will need a change in lifestyle, change in diet, a willingness for the person to actually change – Alternative Therapist 1''

Here we can see a restatement of the points made above, that while the practitioner can give advice, the person must ultimately act upon it, and if they are not willing, then they will not change. The truly cynical could claim that this is because all of these therapies are nothing more than placebo, and this abdication of responsibility is nothing more than a device to conceal their lack of efficacious treatments. But we are not quite so cynical. 

``Yeah, I don't fix people, they have to fix themselves then with support and inspiration from me – Alternative Therapist 2''

This is perhaps the most telling quote in this section. This respondent constructs patients as being totally responsible for their own health, that he merely acts as a facilitator and allows them to heal themselves. This is a very empowering view of the healing process, and contrasts quite strongly with the more paternal constructions of the doctors. 

``how much they'll try to put practices that could be suggested in the clinic into into their lifestyle ammm, you can also I think tell if if they're \ldots you know you point something out to someone, that they can make this subtle  change that will make a huge difference to their bowel habits  
I:mmmm
P:Suggest something for them to eat-
I:mmmm
P: almost on hearing it, I could there could almost be a placebo effect would not be surprised when they come back in two weeks and tell me that their bowel habits have completely changed but I would often almost be able to tell with a patient who's going to do that or who's going to be...... a little bit more open to that or ammm.......how else do I think it works. I I I think a lot of the time with any form of healing I mean, - Alternative Therapist 3''

Again, we have a construction here that points out the differences between people's response to their health. Some other respondents suggest that health is not valued by many, and this respondent argues that some patients will do the work required to get better, while others will not, and that it is this factor which accounts for broadly divergent outcomes. 

``because people think that everything going right comes without any effort and in actual fact, to make things right requires huge effort – Doctor 1''

We have this quote from one of the GP's here, and it supports what the therapists have been saying. One can say that health is being constructed as something which needs to be valued by people if they are to enjoy good health. 

\subsection{Body Knowledge of Health}

Again, this code appeared only in the transcripts of the alternative therapists, and only in two of three of those. Below are some relevant examples with some commentaries on their constructions of health. 

``Because you should more talk to your own wisdom but if you really sick of course you have to go to the doctor – Alternative Therapist 2''

This is an interesting quote, in that it seems to construct an awareness on the part of the person as to the causes and nature of their sickness. The body appears imbued with understanding of the problems facing the person, and this can be consulted. It seems however, that this is only a first resort, as the quote continues to state that serious problems should be dealt with by a doctor.

``By paying attention to what is (pause) going on with yourself. We've simple basic needs. We need to sleep and we need to eat. Basically, those are the two most important we also need to breathe. Otherwise we can – we can name ammm – Alternative Therapist 3''

Here again there is a focus on intenal knowledge. This time, however, it appears constructed in terms of awareness of the body's needs at a more basic level, that of sleeping and eating. This constrasts with the unspecified wisdom referenced in the first quote. 


``P:And to reassure them you know that, everything is OK with them in in some fashion as well and its sustained by (pause) listening to yourself, and listening to nature – Alternative Therapist 3''

Here, from the same respondent we have an expansion of the previous statement. Where first listening to yourself was important, now we have a focus on listening to nature also. While we can construct this as listening to the natural world, this construction could prove quite problematic as there are many different `natures', and this quote does not allow us to distinguish between them. 

\subsection{Environmental Factors}

This next code is interesting, in that it appears  with about the same regularity in the transcripts of both doctors and alternative therapists, which does not occur particularly often throughout the interviews. 

The first example comes from the transcript of Alternative Therapist 1, where they refer to ``a healthy non-toxic environment'' as a major determinant of health. ``And ehhh, gives eh – a safe environment that the person feels safe and releaxed''. We can see here that the conception of the environment here is more of a reference to the sensations and feelings aroused by the environment. 

\section{Construction of Doctors}
\label{sec:construction-doctors}

One of the major themes that emerged from all of the interviews was the nature of doctors, even apart from a more general conception of health practitioners, all the participants focused on the role of doctors in society, and their positive and negative impacts. 

One of the ordinary participants focused on the relationship between Doctors and Alternative therapists, with this excerpt ``I think if you have like serious [pause] health problem, you will need both''. This stresses and indeed this participant stressed throughout the interview, that doctors and alternative therapists should be viewed as complementary rather than opposing. 

\begin{quotation}
  she mentioned this to her GP who (pause) became very angry and asked me to phone him immediately 
I:Mmmm
P:and this type of thing doesn't happen very often. I rang him, and he was quite set, saying I dont want this woman to have more and more treatments, you know and I want I want her to find the right treatment. And I said, so do I, and this is it, and this is what I deem most good for her at the moment and he asked about the treatment and I tried to explain a little – in simple language – and the end of the conversation he was Ok, let's do this. 

\end{quotation}

This quotation came from Alternative therapist 3, and describes the relationship between doctors and alternative therapists. Note that he constructs the two as in a collaborative relationship rather than competing, and shows that they were able to find a good balance between bothe of their particular forms of treatment. 

It is interesting in that one of the doctors focused on their role as agents of social change, particularly in this excerpt

\begin{quotation}
   I think as doctors we have a job maybe as advocates you know to point out the issues, and point out the we may not be have the solutions but we should be able to sortof say these are part of the problems – these are the problems, and these are some of the determinants and really these need sorting out 

\end{quotation}

This quotation focuses on the role of doctors in society rather than their role as a individual health practitioner, making the point that they have a responsibility to their patients to focus on the problems that are actually affecting their abilities to live healthy lives. 

Interestingly, many of the alternative practitioners did not subscribe to this viewpoint of doctors, instead regarding them as prescribers 
\begin{quotation}
  Ehhh, a lot of doctors just ah rely on on on on eh their pharmacuetical companies 

\end{quotation}


The implication here seems to be that the commercial relationships between doctors and pharmacuetical companies get in the way of healing. 

However, this point was actually raised by one of the doctors themselves, in a slightly different context: 

\begin{quotation}
  I think doctors actually should have a ethical obligation to say enough is enough you know and I get actually quite frustrated when I get sent a patient that I actually feel has nohting wrong with them 

\end{quotation}

Here we can see a doctor's frustration at the way in which they are expected to dispense medicines to patients even when they feel there is nothing wrong with them. It is worth noting that the doctors frame this as the patients demands, while to the alternative therapists, this is a relationship in which the doctors have power over the patients. 

The second GP also expressed frustration with this state of affairs, saying that 
\begin{quotation}
  even though you try to spend as much time as you can in terms of health prevention such as immunisation or health promotion by giving advice to people on healthy diets exercise giving up smoking etcetera we do tend to spend most of our time reaching for the pen, prescribing 

\end{quotation}

The sense is that they would like to be able to focus more on the health promotion effects that would actually change the persons state of health, but are corraled by the system into prescribing, as that is something that can be done within the confines of the 30 minutes doctors appointment. 

Also, one of the students expressed some annoyance with elements of the system: 
\begin{quotation}
  well as I say like, just that kind of stuff ammm like plenty of times i've been sick and gone to a doctor and he's given antibiotic and i've taken it and gone thats not helping me at all 

\end{quotation}

The notion is that antibiotics are a default option for many doctors and patients, and for some of the respondents, this is not actually particularly useful. 

\begin{quotation}
not unless you're actually particularly sick like, I think that an awful lot of the time people tend to be a small bit sick and go off to a doctor and get their antibiotics and go this didnt help at all, whereas there was probably no need to go to a doctor in the first place 

\end{quotation}

The quotation above referenced another students answer to the question how often do you go to the doctor. Note that given the age (early twenties) and social status (student) of this respondent this is perhaps not a surprising response.  The theme that comes through here is that doctors can be associated with unnecessary treatments and methods, and that this is a conception shared by all three groups in the sample. 


Another theme that emerged around doctors was that doctors focused more on illness. 

The extract (from Doctor 1) illustrates the point: 

\begin{quotation}
  I suppose sometimes health and ill health, you know, there's not different sides of the same coin
I:mmmm
P: but I suppose we're more set up in our training to deal with ill-health as a concept
I:yeah
P:- than health and particularly how the health services are structured 

\end{quotation}

The participant notes that ill-health gets far more attention than does health, perhaps linking back to the idea that ill-health is a breaking down of something that is normal (i.e. health). 

Another quote from the other Doctor (No 2) supports this reading:

\begin{quotation}
  we'd only get so far, and I think that we essentyially would be more into the disease ahhh ammm diagnosis and cure-

\end{quotation}

It is interesting to note that the doctor first says that they are more into disease, but then shifts their words to diagnosis and care, displaying the focus on ill-health referenced above. 


Perhaps an interesting theme which emerged from the interviews with ordinary people and alternative therapists was that doctors were not that important. The interesting point about this is that by making the point, they were in fact reinforcing the notion of doctors as important. 

\begin{quotation}
  So just to have a regular checkup and stuff checkup and ah, well everything was fine but yeah I don't really know so much about doctors. I think doctors are great if you need them but if you dont need them you shouldn't go to them.  -Alternative Therapist 1

\end{quotation} 

The respondent here proudly proclaims their ignorance of doctors, and introduces some tautologies in that doctors are only necessary if you ``need'' them, but does not define what exactly it is to need doctors. 

\begin{quotation}
  not unless you're actually particularly sick like, I think that an awful lot of the time people tend to be a small bit sick and go off to a doctor and get their antibiotics and go this didnt help at all, whereas there was probably no need to go to a doctor in the first place 

\end{quotation}

Here the respondent focuses on doctors only being important when you are really sick, and argues that people tend to go to doctors for issues which they would not consider important enough. 

The next theme around doctors came from Alternative Therapist 3, where they recall an incident where doctors came to see them. 

\begin{quotation}
  initially came for pain a third came for tiredness very interestingly they all asked to come after-hours 
I:Because they didnt want to be seen
P: By their patients, they know my system and that I do one patient per hour and I dont do two or three rooms like a lot of people do and they were fine with that ammm (pause) one a patient (pause) didnt want necessarily anything other than the main complaint which I think was stress ammm but I asked could I treat for other matters 

\end{quotation}

The interesting part here is that he constructs this incident as something out of the ordinary (whereas the converse is broadly accepted by all participants) and frames it as a series of differences between the doctor's typical practice versus that of the alternative practitioner. Note also that the doctor only wanted treatment for the main presenting symptom, rather than a more general process which the alternative therapist would have preferred. 

Another intriuging theme that came through from one of the doctors was the following: 

\begin{quotation}
  the herbalists, who have almost taken on a bio-medical model then a bio-medical sortof way of acting they see patients they diagnose they have a pharmacy of herbs-

\end{quotation}

The participant was responding to a question around whether or not they had any faith in alternative medicines and treatments. Note how the ``good'' alternative therapists are defined by their adherence to the bio-medical model, and note that the other salient features are diagnosis and pharmacies. 

However, note the contrast here with how one of the alternative therapists describes their relationship with doctors. 

\begin{quotation}
  I've become much more in happier terms today with it because of with the fertility side of things I need to rely on blood results a lot. I need people to go and have their hormones checked and and something like sperm analysis, I need, I need medical science completely for this these reasons.
- Alternative Therapist 3
\end{quotation}

This respondent regards their relationship with medical science as non-adversarial, but rather complementary. The contrast with the attitude of the doctor is quite striking. 


\begin{quotation}
  they just prescribe medication that has a lot of side effects and they don't really spend much time with you and you go to the doctor there's very few doctors which actually spend time and actually talk to people and really see where the problem comes from-
Alternative Therapist 1
\end{quotation}

Here, the conception of doctors is as seen earlier, distant prescrivers who do not actually spend time with a person. The implied contrast with their own practice is apparent. 

Even some of the Doctor (No 1) respondents argue in this point:

\begin{quotation}
  I would disagree with what my colleagues might do or i've occasionally been shocked ammm by what I would perceive to be a lack of care,

\end{quotation}

Here it is constructed more in terms of professional disagreement, and the occassional problem, whereas the alternative therapists are more fortright about this (but less so about the problems with their own profession). 

And from one of the Doctor participants: 

\begin{quotation}
  ammm, a bit, I'm not trained in them but obviously I prescribe St John's wort

\end{quotation}

Note the unassuming tone, a bit, expressions of ignorance but the use of obviously to describe the practice of prescribing St John's wort, as though it were the most obvious thing in the world. 

The final theme in relation to doctors was one that has been seen before, the notion of treating symptoms rather than people. 

\begin{quotation}
  there's very few doctors which actually spend time and actually talk to people and really see where the problem comes from
- Alternative Therapist 1.
\end{quotation}

Again (as is quite common in the interviews with the alternative therapists), there is a constrast between ``doctors'' and what the practitioner does. Note that the doctors are noted as not spending time, not talking to people and not getting to the route of the problem, with an implied comparison to the practice of the therapist. 


\begin{quotation}
  they're just trying to ammm [pause] you know [pause] cure the symptoms rather than the origin of the amm, imbalances
-Alternative Therapist 1. 
\end{quotation}

Again, note th contrast, while therapists focus on the origin of problems, doctors treat the symptoms. 

Finally, a doctor gives some credence to this argument, however attributing the blame for this situation elsewhere. 

\begin{quotation}
  then some people are quite happy with a model of you know diagnose me, give me the treatment
-Doctor 2
\end{quotation}

Note here that there is an acceptance that many doctors just treat symptoms, but the blame is placed on the patient for this, who seem to be regarded by the doctor as giving up their own responsibility for health when they see the doctor. 

\section{Diet}
\label{sec:diet}

The next step in the analysis was looking at the codes and themes related to diet. 

\subsubsection{Food as medicine}

This was the most widely utilised code in the entire data-set, appearing over 17 times. This code only appeared in the transcripts of the ordinary people and the alternative therapists, which is why it appears here. 

An example of this code is below:

``in China, they have even the most common person on the street he's a peasant working in the fields are born and and have and inherent knowledge of how to eat in accordance with nature right in their body for a cold condition they know to eat something warm corn soup with ginger or rice casserole, meat and if they've a very very hot condition they know to eat know to eat, you know, cool foods and its very much putting nature into the body looking at external and balancing between the two like I was mentioning a while ago- Alternative Therapist No. 3''

As we can see in from this code, the conception (shared by folk healers across the world) regarding hot and cold foods exists here in his description of health. We can also see how he constructs this as a complement to Western styles of medicine, that it is common knowledge in other, non-traditional societies (where his method is drawn from) but is ignored in our prevalent system of medicine here in the west. 

Another example (from the same participant) follows below:

``I personally do like herbal medicine and I think that its its as close to food as you can get a herb generally grows either above or below ground the roots are usually stronger versions of it so just knowing how herbs work I will use preventative medicines and supplements to protect say if I find working too late head full of information and details, just go for a walk and just try and clear''

Here the participant is talking about what he does when he is sick, and we see how he legitimises herbal medicines by linking them with food, which he has previously described as the best method for promotion of health. 

``good food –- healthy food organic food''. Alternative Therapist No. 1
We can see here (this participant tended to give very short answers to questions) that the emphasis on food is common to the alternative therapists here. We can also note the linkage of health food, organic food as possibly indicating some disquiet with the technocractic nature of herbal medicine. 

\subsection{Diet as Fashion}
\label{sec:diet-as-fashion}

\begin{quotation}
  So, we've a habit of here in the west of -again, going back to diet – people will eat any food at any time and ammm ammm menus in this country have become cosmopolitan palatable ammm you know, fashion as a menu read, or if you're choosing off  a menu be choosing for what the needs are
Alternative Therapist 3. 
\end{quotation}

Here the notion is of food as a lifestyle accessory for mnay people, contrasted to the actual needs. Some of the thoughts of this therapist on useful foods are discussed below. 

\begin{quotation}
  Nor is it sustaining your health to eat cold salads all the way through winter, and yet people will do that
Alternative Therapist 3
\end{quotation}

Again, there is the notion here that certain foods make much more sense at different times of the year, and a certain sense of the disregard of people for what is obvious to the practitioner 

%link this in with similar sentences from doctors. 


\subsection{Diet as Place Based}
\label{sec:diet-as-place}

\begin{quotation}
  So not everyone wants to eat hot spicy foods because you know, hot spicy foods are designed for countries like India you know, Bangladesh and Southern China the hottest spices in the world where its incredibly hot and they eat these foods to open pores, to sweat and to purge-
I:mmmmm
P:to balance themselves with the he-weather whereas we eat them here because its trendy to eat something with chilli.
(Alternative Therapist 3)
\end{quotation}

Here again, the notion is developed of certain foods being appropriate for certain places but not others, and again the idea of ``fashion'' is developed when discussing the food habits of their patients. 

\subsection{Nutrition}
\label{sec:nutrition}

The final section in the food themes constructed was one of nutrition. 

\begin{quotation}
  healthy food organic food
Alternative Therapist 1
\end{quotation}

Again, here the notion is developed that healthy food is organic food. This harks back to much of the focus of the alternative therapists of perceived naturalness and sensitivity to the environment. 

\begin{quotation}
  Yeah, but again it will need a change in lifestyle, change in diet, a willingness for the person to actually change 
Alternative Therapist 1
\end{quotation}

Here again, the notion is developed that the change in diet must be accompanied by further changes, that the levels of change are in some way connected. 

\begin{quotation}
  would support myself then with ehhhh, supplements and ehhhh, ehhh, herbs, homeopathy, [pause] and a diet
Alternative Therapist 1
\end{quotation}

Here, the notion is that supplements are important (as distinct from pharmaeucticals), and that diet is one part of an overarching system. 

\begin{quotation}
  
 they say most of the time, you know, what you take too much sugar your body also reacts on that 
Alternative Therapist 3
\end{quotation}

Here, we have another alternative therapist is describing the opinions they have regarding nutrition (and especially sugar). Note that the speaker distances themselves from the utterance, by suggesting that ``they'' say this rather than expressing his or her own beliefs directly. 

\begin{quotation}
  taking the energy from your food and translating that into nutrition into energy and accommodating that and then expelling energy and expelling waste products efficiently that's the physical side of things energy then
Alternative Therapist 3
\end{quotation}

Here we have a succint description of one of the therapist's point of view of physicality. Note that this is all framed in terms of energy, as are the therapists own treatments. While the description is accurate, the contention is that this physical level is just one amongst many. 

\begin{quotation}
  You need physical, you need food so food is the essence
Alternative Therapist 3
\end{quotation}

Here again we see that the speaker focuses on food and diet as being extremely important for health, but this is also framed within the greater context of essence and energy. 

\begin{quotation}
 right in their body for a cold condition they know to eat something warm corn soup with ginger or rice casserole, meat and if they've a very very hot condition they know to eat know to eat, you know, cool foods and its very much putting nature into the body looking at external and balancing between the two like I was mentioning a while ago


\end{quotation}

Here we have the juxtaposition of the notion of hot and cold foods in the speaker's words. The idea is that there is a balance between hot and cold (or dry and moist) which is an idea which occurs in the philsophies of many older cultures. 

\begin{quotation}
   health promoted and sustained as I said dietary is obviously the No 1
Alternative Therapist 1
\end{quotation}

Here again we see that this speaker focuses on diet as the most important driver of health. 


 \begin{quotation}
 the most important thing that they can leave the room with is an understanding of how to eat over the next month to maintain their health or keep it well.    
Alternative Therapist 3
 \end{quotation}

Here we see the therapists answer to how health can be promoted and sustained, which is that diet is the most important factor in maintaining a healthy standard of living. 

\begin{quotation}
  But really my (pause) ammm strongest push on it would be dietary means-

\end{quotation}

\begin{quotation}
  what I would do is I will watch for the wanring symptoms, cold and cough a lot of people in very close perimeter ammm, you know, dietary side of things, if I notice anything thats a little out of kilter I'll try and address it through diet try and you know a-ahhhh you know yourself very well, ammm in the system of medicine cos you do so much detailed consultations with people it difficult not to think in the same way about yourself

\end{quotation}

Here we see his conception of how his treatments work, and how his health is maintained. Note that he frames this as a continuous process, paying attention to his somatic sensations and then remedying any deficiencies through diet. There is also an acceptance that what you do for your own health is strongly shaped by the treatments that you provide for others. 

\begin{quotation}
  Apart from that I suppose irish people in particular I think especially people in college mightn't know ammm how to eat nutrititious foods properly or how to they mightn't get regular exercise I think they obviously have a good contributing factor to that too like
Student 1
\end{quotation}


Note that here the framing is that individuals lack knowledge about the best nutritional choices to make, rather than that is comes from any sense of ``fashion''. Again, it is interesting that it is framed as Irish people in particular rather than people in general. 

\begin{quotation}
   I would feel you know therapy or ammm there'd be you know certain foods that might help in the diet or what have you and then that can lead to positive mental health for example
Student 2
\end{quotation}

Again, here the final quote refers to foods that ar important for both physical and mental health, in that eating particular foods is framed as being somewhat causal for both physical and mental health. In this, the respondent is linking to some of the other themes around the linking of body and mind. 

\section{Models of Health}
\label{sec:models-health}

The next set of themes deal with the conception of health by different respondents. 

\subsection{Health as balance}
\label{sec:health-as-balance}

Health as balance was a theme that emerged primarily from the interviews with alternative therapists, and to a less extent, from the interviews with students. 

\begin{quotation}
  and I try to find out what ammmm, [pause] where I went off balance 
Alternative Therapist 1
\end{quotation}

Here, the respondent is talking about what the causes of sickness are. There is no mention of external forces here and the conception is that getting out of balance appears to be a primary driver for less than optimal health. 

\begin{quotation}
  kindof things back in balance
Alternative Therapist 1
\end{quotation}

Here, when talking about getting well, the same metaphor is used to describe this process. The difficulty here though, is figuring out exactly what kind of balance the respondent is talking about. 

The words of another alternative therapist may prove useful here. 
\begin{quotation}
  mind and body, you know that kind of a balance 
Alternative Therapist 2
\end{quotation}

Here the balance is between mind and body, harking back to the old saying about a healthy body in a healthy mind. 


\begin{quotation}
  emotional energy has to be very well balanced
Alternative Therapist 3.
\end{quotation}

Here we see the linking of the notion of balance to the notion of energy, which were two key themes which emerged from the interviews with the alternative therapists. 

\begin{quotation}
  right in their body for a cold condition they know to eat something warm corn soup with ginger or rice casserole, meat and if they've a very very hot condition they know to eat know to eat, you know, cool foods and its very much putting nature into the body looking at external and balancing between the two like I was mentioning a while ago

\end{quotation}

Here again it can be seen that the respondent links the notion of balance back into the system of hot and cold foods and their impact on diet. This theme of balance seems to pervade the interviews with the alternative therapists. 

\begin{quotation}
then again maintaining heath its all about balance, so you don't leave it too on one side cos you leave yourself too open ammm you know, there has to be balance within it.
Alternative Therapist 3
\end{quotation}

The theme of balance comes through here, as even balance is regarded as something to be balanced. 


\begin{quotation}
   So these are the processes in the mind, so again, health in respect to that, to emotions, mental energy very much keeping on a balanced level

\end{quotation}

Again we see that balance is to be achieved between emotions and mental thought, expressed in this language of energy (while using quite physical metaphors, level, for instance). 

\begin{quotation}
  sickness are?
P:Same thing, the imbalance-
I:mmmm
P:Of emotions, imbalance of mental thinking imbalance of sleep not sleep to much sleep ahhh and then what you're putting into the body obviously, and also what you're putting into the body if you're sitting in front of a computer for too long, if you're sitting in front of a TV too long, you're putting too much electromagnetic energy on the mobile phone for too long so generally, ammm so you've cardio-vascular health we need balance there-
Alternative Therapist 3
\end{quotation}

Here again the focus is on sickness as being caused by a lack of balance, however, balance is construed in a much broader sense in that particular impacts of the environment can have large effects on health and need to be balanced in particular ways. For the respondents it seems like health is contructed by a process of figuring out what is needed to offset the effects of the environment. 


\subsection{Health as Change}
\label{sec:health-as-change}

The next set of codes that were built into a theme is that of health as change. 

\begin{quotation}
  awareness to – to want to get healthy and change 
  Alternative Therapist 1
\end{quotation}

Here, awareness is constructed as the causal factor, but health and changed are paired together. To some extent, this can also be read as movement from a less good place to a better one. 
The next code makes this clearer.

\begin{quotation}
  a change in lifestyle, change in diet, a willingness for the person to actually change 

\end{quotation}

Here the change itself is focused on, and this theme is reinforced with the use of the term actually, to emphasise that change is primary in this conception. 

\begin{quotation}
  So thats basically it. The same thing with the emotions, keeping them moving, keeping them flowing, ammmm 
Alternative Therapist 3
\end{quotation}

Here this theme is developed in a rather matter-of-fact way, that this movement from one place or state to another is at the heart of health. 

\subsection{Health As Harmony}
\label{sec:health-as-harmony}

\begin{quotation}
   So for example, when again the question what does health mean its being its it sounds very cliched but living in accordance with nature.
Alternative Therapist 3
\end{quotation}

Again, the respondent constructs health in terms of being in balance (c.f. earlier quotes in the health as balance section),  and living in accordance with nature, although nature is never defined in this statement. 

\begin{quotation}
   in China, they have even the most common person on the street he's a peasant working in the fields are born and and have and inherent knowledge of how to eat in accordance with nature 
Alternative Therapist 3
\end{quotation}

Here we have the typical conceit that exotic places have knowledge that is more true that those around us. The conception of China is perhaps idealised, but the theme is that we as Westerners are somehow disconnected from our ``true'' ``nature''. 

\begin{quotation}
  :And to reassure them you know that, everything is OK with them in in some fashion as well and its sustained by (pause) listening to yourself, and listening to nature

\end{quotation}

This particular quote is interesting, in that it links the beliefs noted above with the practice of working with patients. Again, the conception is around being receptive to the internal and external signals of the world. 

\begin{quotation}
  But in China they wouldn't do that Could be, you know, they'd order any person on the street would not eat salad during the winter cos they know its the food is cold energetically 

\end{quotation}

Here again the use of the Chinese as a foil to the people around the respondent, and the contrast to his current patients (see the Food as Fashion section). Note that the respondents starts with a positive statement, and yet continues with a declaration of what these people wouldn't do, suggesting that this is framed in a positive light. 

\begin{quotation}
  Its kindof similar same thing that macrobiotics from Japan eating in accordance with nature, eating the foods that grow around you and you know work we're coming into winter now, so eating root veg is more – is much better idea than eating veg that grow above the ground because when the frost come, they will die anyway

\end{quotation}

Here again, it can be seen that the notion is to be in harmony with the internal and external environment. The focus here is on food, but the general theme reappears again and again in excerpts from this participant. 

\subsection{Health as Social Issue}
\label{sec:health-as-social}


\begin{quotation}
  Yeah, I think it would help, but I also think even simpler things even going to the doctor you see is prioritising health
I:mmmm
P: and health is not a medical problem, health is a social issue you know
Doctor 1
\end{quotation}

This quote emphasises the difficulty with health for many doctors, the profession focuses on solving problems (i.e. symptoms) but ``health is not a problem''. The doctor constructs health as being far broader than sickness, as a matter for society rather than the doctor. 

\begin{quotation}
  and health is wider than just a doctor its everybody-
I:yeah, yeah, yeah
P: and society's problem 
I:- society's problem as it were

\end{quotation}

This quote reinforces the previous excerpt, in that health is framed as everybody's responsibility. To some extent, this is a tactic which shifts attention away from the responsibilities of the respondent, but it seems to be a relatively useful insight. 

\begin{quotation}
  well I think first of all its something that is beyond the realm of the health practitioner 
Doctor 2
\end{quotation}

Here again, the other doctor respondent focuses on health as something beyond any practitioner. It is interesting that both doctors respond like this, in effect throwing up their hands at the whole matter. 

\begin{quotation}
  so in a sense, we're there to pick up the pieces, ahhh while we have a role in health prevention and and actually disease prevention, health promotion ahhh there's an awful lot of other people right down to the individual themselves who have a huge role to play in that
Doctor 2
\end{quotation}

The key excerpt here is the first sentence --- that doctors are there to pick up the pieces, rather than to ensure that they do not get broken in  the first place. The respondent references the whole health care system before they consider the role of the individual. It is interesting to contrast this kind of approach to that of the alternative therapists. 

\begin{quotation}
  
Ill health is 
I: - a medical problem 
P: is a medical problem, but good health is much more ammm wider
I:yeah 
Doctor 1
\end{quotation}

Here the contrast between sickness and health is made explicit in that health is constructed as being much more encompassing than is ill-health. Again, the doctor states that this problem does not lie within the parlance of medicine. 

\begin{quotation}
  there's positive attributes as well as the absence of the negatives

\end{quotation}
Again here the notion is made explicit --- health is not merely the absence of sickness, but rather a thing unto itself. 

\subsection{Health is not a Problem}
\label{sec:health-not-problem}

\begin{quotation}
  health is not.....you know, ill-health is a problem but good health is something that you need to invest your time in it, and unless you make that a priority for yourself you're not gonna
I: you're not gonna have it
P: you're not gonna do it-
I:mmmm
Doctor 1
\end{quotation}


Here again health is constructed as something that requires active work, in that it is not easy to get and needs to be made a ``priority''. Again, note the response to the interviewer, the replacement of possessing health with performing actions that result in health. 


\begin{quotation}
    and health is wider than just a doctor its everybody-
I:yeah, yeah, yeah
P: and society's problem 
Doctor 1
\end{quotation}

Note the contrast here between the earlier statments around health - now it is framed as a problem, but not a problem for doctors, rather it is constructed as society's problem. 


\subsection{Health is not a priority}
\label{sec:health-not-priority}

\begin{quotation}
  health is and like a lot of people I would encounter who might have what I consider maybe not a great prognosis in life in terms of-
I:mmmm
P: their lifestyle 
I:mmmm
P: there's not always even loads of people aren't willing to change but I think they don't prioritise it 
I:mmmm
P:whereas other people will 
I:will, yeah
P: and I don't really understand why that is 

Doctor 1
\end{quotation}
Here we have the construction of health as something which can either be paid attention to or not, and the admission of ignorance from the respondent as to why this occurs. 

\begin{quotation}
  you know, I think time people get sick because they're not doing the basic things required to just keep your body in a modicum of health people just they don't really care I suppose, or I wouldn't even say care, they don't want to get sick, but they downplay in their head the importance of kindof basic things like that, they really think that no, no, its fine if I don't eat today
Student 3
\end{quotation}


Here we have the same notion from a different perspective. Again, the lack of focus on health is constructed as the driver of this problem by both respondents. To a certain extent this reflects their pre-occupations, given that they are both focused on maintaining their own health, but there may bne something behind these statements. 

\subsection{Linking Body and Mind}

Again, this code only appears in the transcripts of alternative practitioners and students, and is conspicuous by its absence throughout the transcripts of the General Practitioners. 

Some examples of this code follow below. 

`` like I would press certain acupuncture points, work certain energy channels...
I: mmmm
P: Through- which are directly applied on to the body so the focus of the person goes to those places – Alternative Therapist 1''

As one can see from this quote, this participant links physical manipulations of the body as having correlations to mental and emotional states. This is interesting as it is, in one sense, an extension of the idea of a healthy mind in a healthy body. 

``Yeah. Well, in in in again with every organ in the body there's there's associated emotions and there's pluses and minuses with that. So for example, we take an organ like the liver the liver ahhhh If we're totally overworked and ammm ehhh the liver can become very excitable and the energy of the liver it it it its a huge organ its it stores almost all of our blood – Alternative Therapist 3''

From this quote above, we can see a similar process to that observed from the first quote under this code heading. For this participant, emotional awareness can be correlated with the state of particular physical organs. Its interesting in that this is something which would probably never be done in psychology, as emotions would be regarded as being neural events rather than being distributed throughout the body. 

``Same thing with the heart If the heart is healthy, you experience joy 
I:Mmmmm
P:We find things funny, we like people, you know we think the best of every single person we meet 
I:Mmmm
P:When the heart is downtrodden and its there's so many expressions – my heart was broken or my heart sank when I heard that news so (pause) even in the lairs of that – Alternative Therapist 3''

Again, we see a cognate description here, where emotions are embodied in the organs and orificies of the body, rather than dissociated from these in the brain/mind. Its perhaps a radical dissolution of the traditional dualism that pervades Western european thinking. For this respondent the locus of emotion is embodied in the very physical structures that make up the body, rather than being something that sits on top of it, in the psychological or medical conceptions of emotion. 

\subsection{Linking Levels}

This code is quite similar to the Linking Body and Mind code, but there are some important differences which we will explore below. 

``trouble with knees, have often ehhhh, a [pause] a relationship to, to to, the what direction you take in life – Alternative Therapist 1''

``your hands 
I: mmmm
P: what have you, how you handle things – Alternative Therapist 1''

``You know like your digestive system often is affected of how you digest life – Alternative Therapist''


We can see from these extracts that the respondent is linking problems of a physical nature to mental and emotional states. This excerpt tends to use argument by analogy which is not usually accepted as proof, but it does provide some insight into the construction of health by this participant. These quotes imply that the entire person is considered as one entity, and that any change in emotions, mental and physical issues will have an impact on all of the other areas. 

``breathe our emotions – Alternative Therapist 3''

``Breathing emotions and leaving them out – Alternative Therapist 3''

We see here again evidence of an extremely holistic approach to the person, where emotional expression can be linked to breathing. It is perhaps interesting in this sense that an old word for life energy was prana, which was also the word for breath, A similar observation can be made about the Greek pneuma, which means both spirit and breath. The Hebrews also used the same word for breath as for emotions (Ruach), all of which points to the commonality of these ideas throughout history. 
``probably equally important I presume it seems like kindof one feeds off the other if you're physically sick, chances are you're not going to be too well mentally, or if you're mentally you're probably not going to be too well physically – Alternative Therapist 3''

Here we can see a recognition of the interdependence of the differing parts of the human organism and the idea that one of them can throw the others off their functioning. 

\subsection{More Than Physical}
\label{sec:more-than-physical}

\begin{quotation}
  ammmm I suppose you can look at it in different ways ammm I think it goes beyond biological 
Doctor 1
\end{quotation}

Here we have one of the respondents constructing health as not just the physical. This perhaps links to the conception of health as greater and more all-encompassing than sickness. 

\begin{quotation}
  ammm a lot of people focus in I suppose the biological or physical issues
I:mmmm
P: but usually they're only a very small – well not a very small – but they're only part of of the problem
Doctor 1
\end{quotation}

Again here we see that others are constucted as focusing on the biological, while the respondent regards this as important but not the whole story. Note how the respondent first describes them as very small, and then goes back on this statement to a certain degree. 


\begin{quotation}
and ammm you know certainly sometimes there comes a point with patients where you just have to say look there's no point giving you another drug-
Doctor 1  
\end{quotation}


%not sure if this excerpt fits with this theme. 

\begin{quotation}
  - there's no biological reason for this so we need to explore alternatives 
I:mmmm
P: alternative pathway
Doctor 1
\end{quotation}

Here again, we have the framing as physiological explanations only going so far, but in this case it appears to be framed as an adjunct in the sense that only after the biological explanations are completed are other options considered. 

\begin{quotation}
  yeah, but then you have a duty to to try to bring the patient to the understanding that because bio-medicine doesn't have the answer doesnt mean that your symptoms or your perspective is not valid and really 
Doctor 1
\end{quotation}


The respondent here ratchets back on the previous statment, making it clear that this should be framed in a patient-centred way, and not just in terms of hypochondria or something like that, but to respect the symptoms and try to get to the heart of the issue, wherever the causes may lie. 

\begin{quotation}
  ahhh it it if used in itself it may not answer the whole problem because people come not only with a condition, they come with with a condition attached to their own bodies its got feelings, its got thoughts preconceptions, its got worries, etcetera-
Doctor 2
\end{quotation}


The other doctors views this differently, or at least frames it in a different fashion - here the symptoms are the primary object of interest, but they are attached to people. 

\begin{quotation}
  oh there's a lot more to it than that. Ammm obviously it is physical the physical aspects do lead to psychological and emotional ammm or both so there;s you know its definitely not just physical aspects 

Student 2
\end{quotation}

Here again we have the focus on the physicality of health, but these are framed as impacting on other elements of health - note the use of the term ``leads to'', which seems to suggest this kind of reading. 


\subsection{As Above, So Below}
\label{sec:as-above-so}

\begin{quotation}
  they would also say our rivers are tributaries sorry our veins are like rivers, and capillaries like tributaries 
Alternative Therapist 3. 
\end{quotation}

Here this theme focuses on the relationship between our body and the world, which tends to be a common theme in Chinese thought. There is a sense of reasoning from analogy, but the underlying notion is one of harmony with the environment and its continuity. 

\subsection{Energy Model of Health}
\label{sec:energy-model-health}

\begin{quotation}
  how do I think they work? Well....from doing different treatments....like shiatsu, so which works on the energetic plane
Alternative Therapist 1
\end{quotation}


Here we have the matter-of-fact response that Shiatsu (a Japanese form of massage) works on the energetic plane. This plane is not particularly defined here, or indeed anywhere in the text. 


\begin{quotation}
   you actually work energy channels that ammm...remind....the person to put energy in certain places. Yeah, like I would press certain acupuncture points, work certain energy channels...

\end{quotation}

This is a particularly interesting quote. In some sense, the body is seen as reflecting these energy channels, and the physical act of massage activates them. The most interesting word is remind, which suggests that this is a natural thing which is done, and not any effort on the part of the therapist. 

\begin{quotation}
  it is too easy to say mind body soul but roughly its pretty much that, physical energy, taking the energy from your food and translating that into nutrition into energy and accommodating that and then expelling energy and expelling waste products efficiently that's the physical side of things energy then 
Alternative Therapist 3
\end{quotation}

Here we have the construction as one of different levels (see the Linking Levels code above) where the physical body is perceived as primary, taking energy (in presumably a physical sense) and nourishing the mind and soul. Note that this is again modelled as a cycle, food comes in and waste goes out. 

\begin{quotation}
  physically taking in energy expending it, ammm clearing it out from the body and then ehhh emotional energy, and then mental energy same thing.
- Alternative Therapist 3
\end{quotation}

Here the notion is more fully developed, that physical nourishment is analogous to mental and emotional nourishment, in that they follow the same cycle. 


\begin{quotation}
  If one relation of all of those who take in the right energy your mental energy will be correct. There's emmm very common ahhh which my professor used to say – if ahhh if you want to do exams, if you're studying, eat well. He says the spleen produces your blood your red blood cells 

\end{quotation}

Here again, the same theme is developed in that the physical and mental are interdependent, a theme that also came through from the doctors, but expressed in a very different way. The mental is constructed as being completely inseperable from the physical, and indeed the organs of the body ar imbued with certain elements ``blood'' in Chinese medicine tends not the mean the same thing as it does in Western paradigms. 

\begin{quotation}
   In france they use digestifs, and apertifs, and thats that's the same thing, you know the same as preparing the energetics to assimilate....transform and bring forth the energy from that food very very carefully, and if you do that, then you're going to have Chi and if you've Chi the the character for Chi in Chinese medicine, or sorry in Chinese language ammm the I'll draw for you is is similar to that and basically what it symbolising is a fire, a pot with rice in the pot and steam rising from it so the pot is sitting over the fire cooking the soup 

\end{quotation}

Here again, simple physical practices are cosntructed as being parallel to this system of energetics, and the use of allegory in this system is highlighted. The abstract notion of Chi is linked back to writing and also to an image, emphasising that this abdtract notion is rooted in physical, common conceptions. 


\begin{quotation}
  So again, when you say how do I think it works thats how I think it works as well manipulating energy
I:mmmm
P: ammm, the energy has to be there first day or first place, so someone is very depleted then often I have to make sure I that we get them to a place where they can that I can manipulate energy because if it's not there, I'm only going to deplete them much more


\end{quotation}

Here we can see the relationship between the two practitioners, in that the practitioner can only work with the patient, not actually imposing themselves upon them. The notion of energy is again referenced, but classified as a pre-existing thing within people, and that their energy is used to heal themselves. It is interesting to consider that this implies a model in which the therapist and patient are co-working on the treatment, which is a facet of treatment that is also expressed by the doctors, though in different language. 

\begin{quotation}
  So, thats, in my thinking, in my study my training how I think things are working as well, that I am manipulating pockets of either static or depleted for replete excessively replete some energy in the body and ahhh....
I: that effects change?
P: Yeah, exactly, yeah, yeah. So thats I suppose my limited way of understanding it and the rest then is down to patient cooperation, really, go an

\end{quotation}

Again, this energy is described in very physical metaphors. The energy is stored in pockets, but the practitioner notes that this is merely a personal conception, but that the primary factor is patient co-operation. 



  
\begin{quotation}
  , doctors, etcetera medications ammm because like a lot of the medication or the herbs there's there all like, natural, they're natural sources no chemicals or what have you so putting in a little bit that were, its just not, you know in ourselves and in our body ammmm and its just overall putting that Chi back into us also
Student 2
\end{quotation}

Here we have a similar conception of health, and especially this notion  of energy. Again, the focus is put on self-healing and the notion of the patient as primary. There is a strong focus on ``naturalness'', this is constructed as being an important aspect of a treatment. 

\begin{quotation}
  ammm its very very helpful for people that have say arthritis ammm could be a headache or ammm you know someone suffering from insomnia list goes on, but its just like I find it fascinating that it is is basically the universe is all around us, and thats basically how it works you know energy is coming from the universe and its flowing in through ammm the practitioners hands the recipient ithout having not actually having to touch 
Student No 2
\end{quotation}

Here again, we have a similar conception - the universer is all around us, the power does not come from within ourselves, but rather healing is a property that can be channeled by one person towards another, but in fact is not caused by either of them. 

\begin{quotation}
  ut ammm I I personally find that its its you know it does alleviate pain you know to the highest degreee from my own experience ammm and then reflexology is an old chinese medicine and its – well not medicine but its-
I:diagnosis
P:-yeah, exactly and you have if you can imagine your feet have meridians travelling from your feet that connect with each part of your body and I find that in fact to be my favourite alternative theapy

\end{quotation}

The respondent was here talking about acupuncture. Again, the model of energy is riased, only after talking about how it produces real changes for the respondent. It again is this abstract energy that is legitimised by its effects on the physical. 

\section{Personal Factors}
\label{sec:personal-factors}

The next major section is on personal factors in health.

\subsection{Awareness}
\label{sec:awareness}

\begin{quotation}
  If a person is not willing to work on themselves and to get better, you can do whatever you want, and they-
I: they won't
P: and 
I: so it requires their willingness to take part in the procedure aswell-
P: yes, their awareness-
Alternative Therapist 1
\end{quotation}


Here again, we can see a similar theme as above, where the person undergoing treatment is perceived as primary, and the therapist as an adjkunct to this. 


\begin{quotation}
   If your haemoglobin your iron is low, you don't absorb information as good just to – they say that the thing if you errr if you're studying and you're eating while you're even studying trying to combine the two at a time (pause) there's an expression in Chinese as well to say that you might as well pick up the book and eat it, cos you'll get more nutrition from eating the paper then you will from eating your meal if you don't have conscious intent 
Alternative Therapist 3
\end{quotation}


Here we have the notion that awareness is the key to gaininn nourishment from the physical world. Again, this is constructed as wisdom from others, but there is also a sense of keeping these levels distinct, and focusing on what it is you are doing in the present moment. 

\begin{quotation}
  
By paying attention to what is (pause) going on with yourself.

Alternative Therapist 3
\end{quotation}

\begin{quotation}
  actually yeah, no the entire thing making people aware of the fact of how – how skewed our perceptions of health are a bit cos when I kindof realised it it made me feel about my health quite a bit differently
Student 3
\end{quotation}

\subsubsection{Belief in Treatment Important}
\begin{quotation}
  its something that I believe myself to be more effective and whether that belief tin it being more effective makes it more effective

\end{quotation}


\subsection{Construction of Illness}
\label{sec:construction-illness}

\begin{quotation}
  but usually they're only a very small – well not a very small – but they're only part of of the problem a lot of it is how people will approach that physical problem-
Doctor 1
\end{quotation}

Here  we can see the way in which the doctors construct this notion of needing the buy-in from the patient. It is framed as the way in which someone approaches the problem is key to the outcome. 

\begin{quotation}
  -if they come with a physical issue-
I:mmmm
P:- it would be how they actually understand it, perceive it, the effects it's having on their life ammm the social supports they have around them to deal with it ammm and the effect it will have on them socially in terms of their ability maybe to manage at home to work-
Doctor 1
\end{quotation}

Here again, the patients perception of their problem and its treatment is regarded as important, as is their connections to the social environment. 

\begin{quotation}
  
that sort of thing, so you know ammm yeah, so 
I:Its kinda how they interpret it forms a large part of it
P:yeah, its very much how the patient interprets it-
I:mmmm
P:the problem 
Doctor 1
\end{quotation}

Here again we have a similar kind of statement as coming from the alternative therapists, though constructed with a different lens, the lens of social context. Nonetheless, again, a large burden is placed on the patient by both groups, though in a different fashion. 

\begin{quotation}
  I think your perception of sickness is so different, a lot – sometimes people come to me with what I consider total rubbish and that obviously is quite – you dont say that to them obviously – I acknowledge their concerns, ideas and expectations but you know really in the grand scheme of life its like get on with it-
I:mmmm, mmmm
P: - whereas when you actually see people who are sick-
I:mmmm
P: - it just puts health in perspective maybe 
Doctor 1
\end{quotation}

Here we have how the respondent constructs health themselves, as a result of their experiences with patients. Note that this is framed as making the respodent less likely to worry about their own health, and also their experience of actual sickness makes them less likely to see some reports as actual problems. 


\subsection{Different Needs for Different People}
\label{sec:diff-needs-diff}

\begin{quotation}
  I think  they're good, I think we all work with different groups
Alternative Therapist 2
\end{quotation}

Here we have one of the therapists talking about doctors, note that this is framed in terms of personal choice, in that different forms of health care are modeled as being for different groups of people. 

\begin{quotation}
  Full of different amounts of ammm you know the common misconception of you need everybody needs eight glasses of water a day Maybe I do, maybe you don't If if if if someone puts too much water into their garden the roots sortof become loose and they'll come out too easily. So, in in a some people they need far more water than that. So its such its such a personal thing per each indidivual working out what what needs addressing in their garden, basically
 - Alternative Therapist 3
\end{quotation}

Here we have a similar theme, though expressed in a different fashion. Here the focus is constructed as there being different treatment needs, rather than therapist needs. Note that this is again framed (as is common from this respondent) with environmental/natural metaphors. 

\begin{quotation}
  I always like to be able to gatekeep for people as to what is the most appropriate treatment for them and I think thats a really really good thing
Alternative Therapist 3
\end{quotation}

This particular excerpt is interesting in that it places the respondent in a position of power above the patient, by ``gatekeep''-ing their particular forms of treatment. This is interesting in that it is a theme which comes through in the responses of doctors, but not so much in the responses of therapists. 

\begin{quotation}
  you know that sortof relationship with somebody and you know there's some people I think its like this sortof phrase horses for courses there are some patients who'll get on with certain types of doctors and vice versa
Doctor 1
\end{quotation}

Again we have a construction of different needs for patients which is subtly different from the ones above. Here the construction is that the relationship between patient and practitioner is of primary importance. 

\begin{quotation}
   ammmm because one person might go down the road of therapy but because there may be a chemical imbalance then they may need ammm whether it be alternative medication or ammm you know anti-depressants or something like that ammm sometimes I feel if one doesn't work you should definitely need the other
Student 2
\end{quotation}

The final excerpt from this section focuses on the use of different forms of treatment as differentially impactful on different people. Note that health care is framed in a somewhat ``a-la-carte'' way, in that if one form of treatment doesn't work, then the person should definitely attempt the other. 

\begin{quotation}
  
you know that sortof relationship with somebody and you know there's some people I think its like this sortof phrase horses for courses there are some patients who'll get on with certain types of doctors and vice versa
I:mmmm, mmm
P: we'll even find it within our own practice that some patients will you know, we're all – I work with two other doctors and we're all very different-
I:mmmm
P:- and like within the practice people will even come to different doctors for different problems-
Doctor 1
\end{quotation}

\begin{quotation}
  I haven't heard any particularly negative things people get a lot of good work out of it get a lot of good out of it, things like homeopathy which has no real scientific backing whatsoever well from my viewpoint ammm...seems to have quite a lot of people who feel a lot better afterward
Student 2
\end{quotation}

\subsection{Expectations Differ Across Class}
\label{sec:expect-diff-across}

\begin{quotation}
 i'm not saying that everything is necessarily is good either, but the barriers that are automatically there are whereas if say to somebody maybe from a higher socio-economic group you know really your weight is the biggest problem-
I:mmmm
P: for you you know you need to work on this-
I:mmmm
P:- and look at your lifestyle, your day and how we can work this out ammm and we might talk about gym or personal trainer and they'll be much more.....you know....they just sortof yeah, yeah, my friends do that, or I could do this they dont sortof come with a negative-
I:yeah
P:-viewpoint sometimes you encounter from other people. And I don't think the other people are being negative, I just think that there are practical realities of their life
  Doctor 1
\end{quotation}

Here again we have the focus on class, where the social and environmental situation surrounding people makes it easier or harder to focus on fixing their problems. Note again that typically of the doctors, the focus is placed on the problem, rather than the more holistic viewpoint (which, to be fair, is expressed by the doctors in other excerpts). 


\section{Models of Sickness}
\label{sec:models-sickness}



\subsection{Sickness Part of Life}
\label{sec:sickness-part-life}

\begin{quotation}
  I don't really do much for it the most standard thing is if I get sick I'll make an effort to eat better more regularly, take more fluids, lie down more its all very basic things – in I wouldnt really go for a medical treatment unless i'd be really there's something particularly like as an emergency mostly out of the fact that I tend to view these things as minorly tieing into the thing of you know ill health – I don't really view unhealth as particularly aberrant I suppose. Yeah, no I standard thing would just be to take bed rest take a very very standard boring but am if seriously ill i'd go to a GP or doctor.
Student 2
\end{quotation}

Here is an excerpt from one of the students who were interviewed. Note that sickness is contextualised as quite normal, regarding them as part of typical life. The respondent says that they would focus on bed rest, but if ``seriously ill'' would go see a doctor. This notion of seriousness crops up in the interviews, but it is not clearly defined at any point. 

\begin{quotation}
  I tend to very much go on a go about my daily day the way I would normally -
I:mmmm
P: - because that tends to make me feel a lot better actually kinda kinda go oh I'm sick and sit down for the day and try to recover a lot of the time I actually feel a lot more sick than in a similar circumstance where I had to go out and interact with the world I just by going about my daily day like that keeping to my routine, by basically ignoring how ill I can be -
Student 2
\end{quotation}

Here again we have the same theme repeated, in that sickness is not framed as debilitating, rather it is the actions of ``being sick'' that are framed as being the real problem. Note that this respondent was quite young and healthy, and so has probably not experienced any major health emergencies which would not respond well to this form of treatment. 

\subsection{Sickness from Pathogens}
\label{sec:sickn-from-path}

\begin{quotation}
  I mean obvious ones of course are going to be things like you know, pathogens of some descriptions, like like whatever they are, bacteria or viruses etcetera apart there there's an interaction there of course the integrity of the person's immune system-
Doctor 2
\end{quotation}

Here is the standard bio-medical model of illness, whereby sickness is conceptualised as coming from pathogens and their interaction with the body's immune system. 

\begin{quotation}
  physically viruses, bacteria what in....in very, well I suppose like is the obvious what actually sickness is where sickness comes from
Student 3.
\end{quotation}

Here is the same model, expressed by one of the students. Note that it is ``obvious'' to this respondent, though all of the doctors and practitioners are much more measured around this subject. 


\subsection{Sickness as a Way of Life}
\label{sec:sickness-as-way}

\begin{quotation}
   in a manner that gonna help you, you know and then there are a group of patients who dont actually really want cure and and thats the other sortof side of the coin-
I:mmmm
P:- that you're not going certainly not anymore you're not going for cure in a lot of cases ammm and then there's some people who are sortof eager to stay in a certain perspective-
Doctor 2
\end{quotation}


Here we have sickness conceptualised as something which people actually fight to maintain --- this group of people who don't really want a cure. The other framing in this section is that for many of the illnesses seen by the doctor, there are no good cures, merely maintenance treatments. 


\subsection{Services focus on Illness}
\label{sec:serv-focus-illn}

\begin{quotation}
  I suppose we're more set up in our training to deal with ill-health as a concept-
I:yeah
P:- than health and particularly how the health services are structured that focus on-
I:mmmm
P:- ill-health rather than health promotion. Which is a very very different type of engagement with with the person, I think 
Doctor 1
\end{quotation}

Here we see that the health services are framed as being focused on illness, as is the entire training and socialisation of doctors. 

\begin{quotation}
   and its because we're stuck in the ill-health-
I:mmmm
P: setup and not in the health set-up

\end{quotation}

Note here that it is framed as a large problem ``Stuck'' in the ill-health setup, and not the health setup. Note that this is framed as being a systemic problem, which is a viewpoint which has some merit, but also serves to reduce the responsibility of the practitioners. 

\subsection{Ill-health as Normal}
\label{sec:illhealth-as-normal}

\begin{quotation}
   they do a lot of damaging activities kindof are so used to it, and consider it such an integral – or such a normal part of their life that they don't really view the ill-health they get as a consequence-
I:mmmm
P: - in any way abnormal
Student 3
\end{quotation}

Here we have ill-health being framed as the default state of affairs for many people. It is constructed as both stemming from a lack of awareness of consequences, and as the result of not knowing what health is like. This again reinforces the theme of health/sickness as being personally mediated, which comes through in all respondents, regardless of background. 

\begin{quotation}
  bit. People – people have ill health very much, rather like ammm people aren't particularly healthy I mean even in – even in my earlier it was just an absence of particular ill health, I mean I don't consider I consider being in a relative state of fitness and not particularly healthy to be the normal rather than actually being healthy 
Student 3
\end{quotation}

Again, here sickness is framed as both the absence of health, and also as a lack of awareness of what it means to be healthy. Sickness is framed by this respondent as being the natural state of affairs, rather than something unnatural. In fact, health is framed somewhat as the more unlikely feature of life. 

\subsection{Differences in Immunity}
\label{sec:differences-immunity}

\begin{quotation}
  and so basically those with any type of weakened immunity will be more susceptible if those pathogens get into the body because a lot of us go round with pathogens which wouldnt cause very serious illness in and of themselves but the immune system is dealing with them, and we've got effective barriers to that that infection. So I suppose that there's there';s a number of issues and I suppose that the immunity and sometimes that immunity can be modulated  by by by a person's mental well-being, the levels of stress can weaken that 
Doctor 2
\end{quotation}

Here we have the way in which the mind is perceived to affect the body framed by one of the doctors. Note that this is all very qualified, the use of qualifiers such as ``I suppose'', and ``sometimes'' makes it clear that this is not a particularly strong viewpoint from this respondents perspective. 


\section{Social Dimensions}
\label{sec:social-dimensions}

\subsection{Class Differences}
\label{sec:class-differences}

\begin{quotation}
 say if I've a 45 year old man who comes into me with chest pain and I think its a cough, and he's been smoking and he is working as maybe a builder and he's 4 kids at home and.... you know, thats sortof where he's at....to promote his health takes huge efforts because he has to invest much more in making changes to his diet, his smoking habits and his general social mileu, if you like
Doctor 1.  
\end{quotation}

This excerpt frames health and health problems and the ability for them to be resolved as inextricably linked to the social aspects of this life. The social environment around the person is regarded as something which can exert extremely causative impacts on outcomes. 

\begin{quotation}
  whereas if I have the same man coming from maybe a higher socio-economic group he's expectations of his health are automatically higher-
I:mmmm
P: and he's probably gonna have the leisure time or the money to access the appropriate resources-
I:yeah
P: that are just not available to say my poorer-

\end{quotation}

Here we have the opposite social situation, but with similar symptoms. It is interesting to note that the ``expectations'' around health are regarded as better, given that this theme arises from research into placebo. Again, the focus is on the nature and quality of the social resources available to the patient rather than any physical measure which makes it more likely that one rather than the other would succeed. 

\begin{quotation}
  So for example they did this sortof exercise referral programme here running in cork-
I:right, OK
P: - So I can say to somebody, look i'm gonna refer to the gym and ammm they'll assess your fitness  and then you'll get a reduced rate to the gym-
I:mmmm
P: - and that sounds good but my patients will come back and say ammm I dont have the bus fare to get to the gym of course I would say then you could walk you know I can't transport to the gym is difficult and a lot of the people who we would be referring might have a lot of health issues you know like maybe a bit of arthritis, chest problems-
I:mmmm
P:- so me saying to them walk is just not a runner especially in the rain and you need gear and all that sortof stuff. The second thing then is the waiting list the thrid problem is is reduced rate, but its not free-

Reference 4 - 2.26% Coverage

ammm, i'm not saying that everything is necessarily is good either, but the barriers that are automatically there are whereas if say to somebody maybe from a higher socio-economic group you know really your weight is the biggest problem-
I:mmmm
P: for you you know you need to work on this-
I:mmmm
P:- and look at your lifestyle, your day and how we can work this out ammm and we might talk about gym or personal trainer and they'll be much more.....you know....they just sortof yeah, yeah, my friends do that, or I could do this they dont sortof come with a negative-
I:yeah
P:-viewpoint sometimes you encounter from other people. And I don't think the other people are being negative, I just think that there are practical realities of their life
Doctor 1
\end{quotation}

Again here, the social context of the medical advice is regarded as a primary driver of the outcomes, in that the poorer patients have both lower expectations and less resources to help them to achieve the health goals. The phrase ``practical realities'' both sums up the injustice and references the idea introduced earlier that people have different capacity to actually maintain their health, and most of these factors are entirely outside the control of a health practitioner. 

\begin{quotation}
  :yeah but it it its more than time people from higher socio-economic groups can be working very hard-
I:mmmm
P: aswell like but they value health...they can see the value of health more
I:more, yeah
P:- I think you know
I:yeah
P:ammmm, so....time is an issue, cost is an issue but its also perception of how important-
I:yeah
P:- health is
Doctor 1
\end{quotation}

Again here, the issue is framed as not just one of resources, but rather that people from higher socio-economic groups perceive their health as more important or more pressing than do other people. 


\begin{quotation}
  you know and I can nearly you can sadly nearly predict 
I: who's going to
P: or yeah you can predict ill health from a young age or you can predict sometimes.....people that are more likely to engage encounter maybe trouble

\end{quotation}

Here the issue is framed as a sad fact around the work which the respondent does with people, in that it is easy to see based on the particular socio-economic status whether or not treatment will be effective. Again, there is a subtext of framing this as a problem for society rather than just for doctors. 

\begin{quotation}
  And it comes right down to issues such as you know, equity and and even the imbalance of wealth as well, thats not an easy one to solve well there's a lot of ill health and disease is is vbery much linked with poverty and you can see the differences across socio-economic groups 
Doctor 2
\end{quotation}

Here we have a similar framing of the problem by the other doctor respondent, again there is somewhat more of a framing of this as not something which can be changed, rather it is an unfortunate fact of life for this respondent. 

\begin{quotation}
  yes, it can definitely or it can be just effected through the sufficient funds to go for the cheapest option all the time, and that might not be the healthiest
I:the healthiest option
P: and in terms of choice of foods, for example, maybe going for the take-away or maybe going for, or the skills may not be there to actually produce cook the proper food.
Doctor 2
\end{quotation}

Here it is framed both in terms of money --- ``the cheapest option'' and also in terms of a lack of resources to actually prepare the food. Again, it is framed in a particularly abstract fashion, note the use of the passive voice, which is a common pattern for this respondent. 

\begin{quotation}
   I don't really know why that is its not only money 
I:yeah
P:It is – it is a mindset I think too
Doctor 1
\end{quotation}
 Again, here the problem is framed not only in terms of access to monetary resources, but also as a ``mindset'', which is something which falls outside the purview of doctors. This framing fits quite well with earlier commentary about health as as a social problem. 

\subsection{Family dimension of illness}
\label{sec:family-dimens-illn}

\begin{quotation}
  because a lot of the problems I deal with have been ammm people are nearly reared to them you know. 
Doctor 1
\end{quotation}


Here again, we have many of the problems encountered by the doctor in their practice framed as  being more social than medical. There is a sense in which the environment in which people live is regarded as a major contributing factor towards health or the lack thereof. 

\begin{quotation}
  It is Its a silly way like the health seeking behaviour I have in some of my patients is just totally reared into them I can see it being reared into them 
I:mmmm
P: and some I spend more time on each visit trying to convince them people not to use the antibiotic for example ammm....but they pick up the anxieties from of their family

Doctor 1
\end{quotation}


This excerpt frames the issue as something which is acquired from the social environment, whereby patients demand antibiotics because their family say they need them. There is a certain way in which this is framed as a reason for differential outcomes amongst similar patients, and also as a device by which to explain away poor outcomes. 

\begin{quotation}
  its very frustrating working in a system and I'm thats reared into people the whole depression issue meds are not you know in common parlance the only way to deal with things and then counselling is just too nebulous 
Doctor 1
\end{quotation}

Here we can sense the frustration (explicitly called out in the text) that patients come with their own expectations around treatment, and in some cases the respondent just has to go along with this, to gain any hope of a successful outcome. 

\begin{quotation}
   the origins of ill health, as it were come right from the household level
Doctor 2.
\end{quotation}

Here we can see a similar point being raised by another doctor respondent. It is perhaps interesting to note that family systems are regarded as primary in many cases, the use of the term ``reared'' into them. It is as though the doctors allow themselves to consider some social issues, but only to the family level. Alternatively, this particular framing could be the result of their training only considering the systems up to this level and not wanting to speculate beyond the data. 

\begin{quotation}
  So for example they did this sortof exercise referral programme here running in cork-
I:right, OK
P: - So I can say to somebody, look i'm gonna refer to the gym and ammm they'll assess your fitness  and then you'll get a reduced rate to the gym-
I:mmmm
P: - and that sounds good but my patients will come back and say ammm I dont have the bus fare to get to the gym of course I would say then you could walk you know I can't transport to the gym is difficult and a lot of the people who we would be referring might have a lot of health issues you know like maybe a bit of arthritis, chest problems-
I:mmmm
P:- so me saying to them walk is just not a runner especially in the rain and you need gear and all that sortof stuff. The second thing then is the waiting list the thrid problem is is reduced rate, but its not free-
Doctor 1
\end{quotation}


\begin{quotation}
  ammm, and I suppose if we look at each such as a a part of the effect I suppose, you know, we can also say that link stress to some degree with habits and dangerous habits so to speak such as smoking. Its a two way chan- thing and one can give rise to the other. Twill often be ahh if we look at it, I mean poverty too can give rise to ill health
Doctor 2
\end{quotation}



\section{Development of Repertory Grid}
\label{sec:devel-repert-grid}

The repertory grid approach was taken for the following reasons. Firstly, conventional methods of developing IAT measures use the published self-report scale as a base, but for placebo treatment expectancies, there is no real validated self report measure (the development of which was an aim of this study, reported in Chapter~\ref{cha:tcq-thesis}). 

The first step was the development of stimuli for the repertory grid. This process was carried out along with the first administration of the TCQ, and utilised the same sample. Following the completion of the instrument, participants were asked the following:

\begin{quotation}
  Please rank, in order of importance, any people or qualities you believe are associated with health (use titles not names e.g. doctor, not doctor murphy)

\end{quotation}

<<packages, echo=FALSE, results=hide>>=
require(ggplot2)
require(reshape2)
require(plyr)
require(xtable)
@ 

<<data, echo=FALSE, results=hide>>=
qual <- read.csv("RepGridPeople.csv", stringsAsFactors=FALSE, na.strings="")
qual.m <- melt(qual, id.vars=NULL)
qual.m[,"value"] <- with(qual.m, tolower(value))
qual.tab <- as.data.frame(with(qual.m, table(value)))
qual.tab.sort <- qual.tab[with(qual.tab, order(Freq, decreasing=TRUE)),]
@ 

\begin{figure}
<<plotfreq, echo=FALSE, fig=TRUE>>=
freq.pl<-ggplot(qual.tab.sort[1:20,], aes(x=value, y=Freq))+geom_bar(stat="identity")
print(freq.pl)
@   
  \caption{Histogram of Frequency of People or Qualities}
  \label{fig:freplot}
\end{figure}

<<freqtab, echo=FALSE, results=tex>>=
print(xtable(qual.tab.sort[1:10,], caption="Frequency of Exemplars, Rep Grid Study", label="tab:freqrep"))
@ 

As can be seen from Figure \ref{fig:freplot}, and Table \ref{tab:freqrep} the most popular exemplar for health was (unsurprisingly) doctor, followed by nurse, pharmacist and dentist. Additionally, a rep grid requires adjectives describing the exemplars, and these were taken from the standard repertory grid developed by Kelly.

\subsection{Piloting of the Repertory Grid}
\label{sec:pilot-repert-grid}

This repertory grid (see Appendix) was then piloted with a convenience sample. Unfortunately, it became clear that participants in this sample did not have enough examples of medical professionals in order to be able to accurately fill out the grid. The original pilot was carried out online (N=10) and not one respondent was able to complete the process. This was then followed with an attempt at card-sorting (N=3) where it again became clear that participants simply did not have enough experience with particular medical practitioners and environments, and so this attempt was abandoned. 

\section{Development of IAT}
\label{sec:development-iat}

Therefore, the next step was to develop an IAT without the use of the repertory grid which had been part of the original plan. The approach taken here was two-fold, given the aims of the project. The first step was to use the interviews to establish a common set of themes, and then to match these to the explicit measure, in  order to assure comparability. In the case of the Optimism IAT, this process was simple enough as there existed a self-report measure. However, in the case of the TCQ-IAT this approach presented some problems, as noted previously in this thesis. 

The eventual approach taken was to use forms of treatments for the stimuli, given that these were the closest to the explicit measure, and additionally because they had relatively high face-validity. The positive/negative stimuli were taken to be either words representing truth or falsity. This was done as it was believed that these words would be the most useful. 

The next step in this process was the piloting of the IAT and the examination of their associations with explicit measures of the construct, to ensure that they were measuring related areas. 

<<fileimport, echo=FALSE, results=hide>>=
setwd("ExperimentDataforR/Pilot")
iepilot<-read.csv("I and E for Pilot.csv")
require(psych)
require(xtable)
@

<<scalecreation, echo=FALSE, results=hide>>=
scales<-cbind(iepilot$LOTR, iepilot$MAAS, iepilot$Pill, iepilot$Cream, iepilot$Inj, iepilot$Acu, iepilot$Hom, iepilot$Rei)
optpesswords<-cbind(iepilot$Disimproving, iepilot$Worse, iepilot$Sad, iepilot$Failing, iepilot$Happy, iepilot$Succeeding, iepilot$Better, iepilot$Improving)
@

<<plotscales, echo=FALSE, fig=TRUE>>=
pairs.panels(scales, labels=c(LOTR, MAAS, Pill, Cream, Inj, Acu, Hom, Rei))
@

<<plotoptpess, echo=FALSE, fig=TRUE>>=
pairs.panels(optpesswords, labels=c(Disimproving, Worse, Sad, Failing, Happy, Succeeding, Better, Improving)
@

<<gender, echo=FALSE, results=tex>>=
xtable(summary(iepilot$Gender))	#$
@

<<age, echo=FALSE, results=tex>>=
xtable(summary(iepilot$Age))	#$
@

<<iatscores, echo=FALSE, results=tex>>=
IAT<-cbind(iepilot$DIAT.Conv, iepilot$DiatOPt)
print(xtable(cor.test(IAT, use="complete.obs", method="spearman")))
@

<<maascorr, echo=FALSE, results=tex>>=
print(xtable(cor.test<-(IAT, iepilot$MAAS, use="complete.obs", method="spearman"))) #$
@

<<srcorr, echo=FALSE, results=tex>>=
print(xtable(cor.test<-(iepilot$IATOpt, iepilot$LOTR, use="complete.obs", method="spearman"))) #$
@

%%% Local Variables: 
%%% mode: latex
%%% TeX-master: "PlaceboMeasurementByMultipleMethods"
%%% End: 
